"""new field in user model

Revision ID: 1467bfe9d0ad
Revises: 59a7a62ff754
Create Date: 2024-09-06 19:18:29.497870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1467bfe9d0ad'
down_revision = '59a7a62ff754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
